/// <reference types="cypress" />



describe('Agentes - Área de testes', function(){
    beforeEach(function() {
        cy.visit('./source/formulario.html')
    })
    it('Verifica título da página', function() {
        cy.title()
        .should('be.equal', 'Testando - Champions')
    })
    it('Testando Click em agentes', function(){
        cy.get('.area_agents > :nth-child(1) > img')
        .click()
        cy.get('.img_skill > :nth-child(1) > input')
        .click()
        .should('be.checked')
        .uncheck()
        cy.get('.img_skill > :nth-child(2) > input')
        .click()
        .should('be.checked')
        .uncheck()
        cy.get('.img_skill > :nth-child(3) > input')
        .click()
        .should('be.checked')
        .uncheck()
        cy.get('.img_skill > :nth-child(4) > input')
        .click()
        .should('be.checked')
        .uncheck()
        cy.get('#close_modal')
        .click()


        cy.get('.area_agents > :nth-child(2) > img')
        .click()
        cy.get('.img_skill > :nth-child(1) > input')
        .click()
        .should('be.checked')
        .uncheck()
        cy.get('.img_skill > :nth-child(2) > input')
        .click()
        .should('be.checked')
        .uncheck()
        cy.get('.img_skill > :nth-child(3) > input')
        .click()
        .should('be.checked')
        .uncheck()
        cy.get('.img_skill > :nth-child(4) > input')
        .click()
        .should('be.checked')
        .uncheck()
        cy.get('#close_modal')
        .click()

        cy.get('.area_agents > :nth-child(3) > img')
        .click()
        cy.get('.img_skill > :nth-child(1) > input')
        .click()
        .should('be.checked')
        .uncheck()
        cy.get('.img_skill > :nth-child(2) > input')
        .click()
        .should('be.checked')
        .uncheck()
        cy.get('.img_skill > :nth-child(3) > input')
        .click()
        .should('be.checked')
        .uncheck()
        cy.get('.img_skill > :nth-child(4) > input')
        .click()
        .should('be.checked')
        .uncheck()
        cy.get('#close_modal')
        .click()

        cy.get('.area_agents > :nth-child(4) > img')
        .click()
        cy.get('.img_skill > :nth-child(1) > input')
        .click()
        .should('be.checked')
        .uncheck()
        cy.get('.img_skill > :nth-child(2) > input')
        .click()
        .should('be.checked')
        .uncheck()
        cy.get('.img_skill > :nth-child(3) > input')
        .click()
        .should('be.checked')
        .uncheck()
        cy.get('.img_skill > :nth-child(4) > input')
        .click()
        .should('be.checked')
        .uncheck()
        cy.get('#close_modal')
        .click()

        cy.get('.area_agents > :nth-child(5) > img')
        .click()
        cy.get('.img_skill > :nth-child(1) > input')
        .click()
        .should('be.checked')
        .uncheck()
        cy.get('.img_skill > :nth-child(2) > input')
        .click()
        .should('be.checked')
        .uncheck()
        cy.get('.img_skill > :nth-child(3) > input')
        .click()
        .should('be.checked')
        .uncheck()
        cy.get('.img_skill > :nth-child(4) > input')
        .click()
        .should('be.checked')
        .uncheck()
        cy.get('#close_modal')
        .click()

        cy.get('.area_agents > :nth-child(6) > img')
        .click()
        cy.get('.img_skill > :nth-child(1) > input')
        .click()
        .should('be.checked')
        .uncheck()
        cy.get('.img_skill > :nth-child(2) > input')
        .click()
        .should('be.checked')
        .uncheck()
        cy.get('.img_skill > :nth-child(3) > input')
        .click()
        .should('be.checked')
        .uncheck()
        cy.get('.img_skill > :nth-child(4) > input')
        .click()
        .should('be.checked')
        .uncheck()
        cy.get('#close_modal')
        .click()

        cy.get('.area_agents > :nth-child(7) > img')
        .click()
        cy.get('.img_skill > :nth-child(1) > input')
        .click()
        .should('be.checked')
        .uncheck()
        cy.get('.img_skill > :nth-child(2) > input')
        .click()
        .should('be.checked')
        .uncheck()
        cy.get('.img_skill > :nth-child(3) > input')
        .click()
        .should('be.checked')
        .uncheck()
        cy.get('.img_skill > :nth-child(4) > input')
        .click()
        .should('be.checked')
        .uncheck()
        cy.get('#close_modal')
        .click()

        cy.get('.area_agents > :nth-child(8) > img')
        .click()
        cy.get('.img_skill > :nth-child(1) > input')
        .click()
        .should('be.checked')
        .uncheck()
        cy.get('.img_skill > :nth-child(2) > input')
        .click()
        .should('be.checked')
        .uncheck()
        cy.get('.img_skill > :nth-child(3) > input')
        .click()
        .should('be.checked')
        .uncheck()
        cy.get('.img_skill > :nth-child(4) > input')
        .click()
        .should('be.checked')
        .uncheck()
        cy.get('#close_modal')
        .click()

        cy.get('.area_agents > :nth-child(9) > img')
        .click()
        .click()
        cy.get('.img_skill > :nth-child(1) > input')
        .click()
        .should('be.checked')
        .uncheck()
        cy.get('.img_skill > :nth-child(2) > input')
        .click()
        .should('be.checked')
        .uncheck()
        cy.get('.img_skill > :nth-child(3) > input')
        .click()
        .should('be.checked')
        .uncheck()
        cy.get('.img_skill > :nth-child(4) > input')
        .click()
        .should('be.checked')
        .uncheck()
        cy.get('#close_modal')
        .click()

        cy.get('.area_agents > :nth-child(10) > img')
        .click()
        .click()
        cy.get('.img_skill > :nth-child(1) > input')
        .click()
        .should('be.checked')
        .uncheck()
        cy.get('.img_skill > :nth-child(2) > input')
        .click()
        .should('be.checked')
        .uncheck()
        cy.get('.img_skill > :nth-child(3) > input')
        .click()
        .should('be.checked')
        .uncheck()
        cy.get('.img_skill > :nth-child(4) > input')
        .click()
        .should('be.checked')
        .uncheck()
        cy.get('#close_modal')
        .click()

        cy.get('.area_agents > :nth-child(11) > img')
        .click()
        .click()
        cy.get('.img_skill > :nth-child(1) > input')
        .click()
        .should('be.checked')
        .uncheck()
        cy.get('.img_skill > :nth-child(2) > input')
        .click()
        .should('be.checked')
        .uncheck()
        cy.get('.img_skill > :nth-child(3) > input')
        .click()
        .should('be.checked')
        .uncheck()
        cy.get('.img_skill > :nth-child(4) > input')
        .click()
        .should('be.checked')
        .uncheck()
        cy.get('#close_modal')
        .click()

        cy.get('.area_agents > :nth-child(12) > img')
        .click()
        .click()
        cy.get('.img_skill > :nth-child(1) > input')
        .click()
        .should('be.checked')
        .uncheck()
        cy.get('.img_skill > :nth-child(2) > input')
        .click()
        .should('be.checked')
        .uncheck()
        cy.get('.img_skill > :nth-child(3) > input')
        .click()
        .should('be.checked')
        .uncheck()
        cy.get('.img_skill > :nth-child(4) > input')
        .click()
        .should('be.checked')
        .uncheck()
        cy.get('#close_modal')
        .click()
    })
    it('Logando em conta aleatória', function() {
        cy.get('[placeholder="Login"]')
        .type('Lucas')

        cy.get('[placeholder="Senha"]')
        .type('Senha123')

        cy.get('#button_login')
        .click()
    })
    it('Indo para páginas do header', function() {
        cy.get(':nth-child(1) > .a_target')
        .click()
        cy.contains('Vamos responder a algumas perguntas sobre seu jogo favorito?').should('be.visible')

        cy.get(':nth-child(2) > .a_target')
        .click()
        cy.contains('Jett').should('be.visible')

        cy.get(':nth-child(2) > .a_target')
        .click()
        cy.contains('Jett').should('be.visible')

        cy.get(':nth-child(3) > .a_target')
        .click()
        cy.contains('Ascent').should('be.visible')
        cy.get(':nth-child(2) > .a_target')
        .click()
        cy.contains('Jett').should('be.visible')

        cy.get(':nth-child(4) > .a_target')
        .click()
        cy.contains('Fale conosco').should('be.visible')
        cy.get(':nth-child(2) > .a_target')
        .click()
        cy.contains('Jett').should('be.visible')

    })
})
